### PR TITLE
allow password field

### PR DESCRIPTION
**Pull request by NileshPatel17**

### CODE REVIEW

**Comment by NileshPatel17** [comment]
@naveenvignesh5 please let me know if we can add this feature to allow to act as password field

**Comment by NileshPatel17** [comment]
https://user-images.githubusercontent.com/27020381/219545869-11361682-f6b1-4808-8d9d-96f7d049d6e2.mov

**Comment by mstrokin** [comment]
You can just use this, as props are passed down to TextInput

<OTPTextView
          secureTextEntry={true}
/>

**Comment by naveenvignesh5** [comment]
Based on @mstrokin's comment, as you can the intended functionality can be achieved with passing the **secureTextEntry** prop. So closing this PR.

**Pull request closed without merging**
